# Generated by Django 6.0.2 on 2026-05-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_course_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('students', models.CharField(max_length=100)),
                ('learn_1', models.CharField(max_length=300)),
                ('learn_2', models.CharField(max_length=300)),
                ('learn_3', models.CharField(max_length=300)),
                ('learn_4', models.CharField(max_length=300)),
                ('learn_5', models.CharField(max_length=300)),
                ('learn_6', models.CharField(max_length=300)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.course')),
            ],
        ),
    ]
