# Generated by Django 6.0.2 on 2026-05-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_courseprogress_coursevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
    ]
