# Generated by Django 6.0.2 on 2026-05-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_remove_coursevideo_youtube_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='video_file',
            field=models.FileField(upload_to='course_videos/'),
        ),
    ]
