# Generated by Django 6.0.2 on 2026-05-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_assessment_aiquestion_studentanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIQuiz',
        ),
    ]
