# Generated by Django 6.0.2 on 2026-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_delete_aiquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquestion',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=50),
        ),
        migrations.AddField(
            model_name='aiquestion',
            name='topic',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
